extern "C" {
#include "../../../WebGLPlugins/lapi.c"
#include "../../../WebGLPlugins/lauxlib.c"
#include "../../../WebGLPlugins/lbaselib.c"
#include "../../../WebGLPlugins/lbitlib.c"
#include "../../../WebGLPlugins/lcode.c"
#include "../../../WebGLPlugins/lcorolib.c"
#include "../../../WebGLPlugins/lctype.c"
#include "../../../WebGLPlugins/ldblib.c"
#include "../../../WebGLPlugins/ldebug.c"
#include "../../../WebGLPlugins/ldo.c"
#include "../../../WebGLPlugins/ldump.c"
#include "../../../WebGLPlugins/lfunc.c"
#include "../../../WebGLPlugins/lgc.c"
#include "../../../WebGLPlugins/linit.c"
#include "../../../WebGLPlugins/liolib.c"
#include "../../../WebGLPlugins/llex.c"
#include "../../../WebGLPlugins/lmathlib.c"
#include "../../../WebGLPlugins/lmem.c"
#include "../../../WebGLPlugins/loadlib.c"
#include "../../../WebGLPlugins/lobject.c"
#include "../../../WebGLPlugins/lopcodes.c"
#include "../../../WebGLPlugins/loslib.c"
#include "../../../WebGLPlugins/lparser.c"
#include "../../../WebGLPlugins/lstate.c"
#include "../../../WebGLPlugins/lstring.c"
#include "../../../WebGLPlugins/lstrlib.c"
#include "../../../WebGLPlugins/ltable.c"
#include "../../../WebGLPlugins/ltablib.c"
#include "../../../WebGLPlugins/ltm.c"
#include "../../../WebGLPlugins/lundump.c"
#include "../../../WebGLPlugins/lutf8lib.c"
#include "../../../WebGLPlugins/lvm.c"
#include "../../../WebGLPlugins/lzio.c"
#include "../../../WebGLPlugins/i64lib.c"
#include "../../../WebGLPlugins/perflib.c"
#include "../../../WebGLPlugins/xlua.c"
}



